baseURL = "https://blog.codefastdieyoung.org/"
languageCode = "en-us"
title = "Code fast, die young"

pygmentsCodeFences = true

disqusShortname = "blog-codefastdieyoung-xyz" #Disqus shortname
googleAnalytics = "UA-28956594-2" #Google Analytics ID

theme = "kiera"

[author]
    name = "Yurii Ostapchuk"       #Author name
    github = "thatwist"     #Github username
    #gitlab = ""     #Gitlab username
    linkedin = "yurii-ostapchuk"   #LinkedIn username
    facebook = "twisttwist"   #Facebook username
    twitter = "twist522"    #Twitter username
    instagram = "twist522"  #Instagram username

[params]
    tagline = "Spark, Scala, Data and a pinch of rationalism"
